# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-14 12:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='engiProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('company', models.CharField(blank=True, max_length=140)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil ingeniero',
                'verbose_name_plural': 'Listado de perfiles',
            },
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estado del ingeniero',
                'verbose_name_plural': 'Listado Estados del ingeniero',
            },
        ),
        migrations.CreateModel(
            name='statusEngineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estado del ingeniero',
                'verbose_name_plural': 'Listado Estados del ingeniero',
            },
        ),
    ]
