# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-14 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusengineer',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineer.engiProfile'),
        ),
        migrations.AlterField(
            model_name='statusengineer',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineer.status'),
        ),
    ]
