# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-01 23:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nano', models.CharField(blank=True, max_length=150)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=150)),
                ('startTime', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('address_details', models.CharField(blank=True, max_length=150)),
                ('lat', models.CharField(blank=True, max_length=150)),
                ('lng', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('job_description', models.CharField(blank=True, max_length=150)),
                ('notes_engineer', models.CharField(blank=True, max_length=150)),
                ('required_testing', models.CharField(blank=True, max_length=150)),
                ('site_contact', models.CharField(blank=True, max_length=150)),
                ('site_contact_number', models.CharField(blank=True, max_length=150)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.activities')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'listado de tareas',
            },
        ),
    ]
