# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-02 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20180302_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
