# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-07 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20180302_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='statusTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('description', models.CharField(blank=True, max_length=252)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'estado de la tarea',
                'verbose_name_plural': 'listado de estados de la tarea',
            },
        ),
    ]
