# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-07 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_task_extend_tasktrackingstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='task_extend',
            new_name='taskExtend',
        ),
    ]
